name: Auto YouTube Shorts – Crime (3D Enhanced)

on:
  workflow_dispatch:
    inputs:
      use_3d:
        description: 'Use 3D video generation'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

  schedule:
    - cron: "0 12 * * *"

concurrency:
  group: yt-shorts-upload
  cancel-in-progress: true

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 70

    permissions:
      contents: write

    env:
      PYTHONUNBUFFERED: "1"
      PIP_NO_CACHE_DIR: "1"
      USE_3D_VIDEO: ${{ github.event.inputs.use_3d || 'false' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show execution time
        run: |
          echo "UTC time:   $(date -u)"
          echo "Local time: $(date)"
          echo "3D Mode:    $USE_3D_VIDEO"

      - name: Free disk space
        run: |
          set -euo pipefail
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo rm -rf /usr/share/swift /var/lib/apt/lists/*
          df -h

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          set -euo pipefail
          sudo apt-get update
          
          # Core dependencies
          sudo apt-get install -y ffmpeg
          
          # 3D rendering dependencies (if using 3D)
          if [ "$USE_3D_VIDEO" = "true" ]; then
            sudo apt-get install -y \
              libgl1-mesa-glx \
              libglib2.0-0 \
              xvfb
          fi
          
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          # Install 3D dependencies if enabled
          if [ "$USE_3D_VIDEO" = "true" ] && [ -f requirements_3d.txt ]; then
            pip install -r requirements_3d.txt
          fi

      - name: Setup display for 3D rendering
        if: env.USE_3D_VIDEO == 'true'
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 2

      - name: Select case
        run: |
          set -euo pipefail
          python case_search.py
          test -f case.json

      - name: Generate script
        env:
          GH_MODELS_TOKEN: ${{ secrets.GH_MODELS_TOKEN }}
        run: |
          set -euo pipefail
          python script.py
          test -f script.txt
          test -f beats.json

      - name: Generate narration
        run: |
          set -euo pipefail
          python tts_generate.py --output final_audio.wav
          test -f final_audio.wav

      - name: Build subtitles
        run: |
          set -euo pipefail
          python subtitles_build.py
          test -f subs.ass

      - name: Validate gameplay loops
        run: |
          set -euo pipefail
          test "$(ls gameplay/loops/*.mp4 | wc -l)" -ge 1

      # NEW: 3D Video Generation (optional)
      - name: Build 3D video
        if: env.USE_3D_VIDEO == 'true'
        env:
          DISPLAY: :99
        run: |
          set -euo pipefail
          if [ -f video_3d_build.py ]; then
            python video_3d_build.py
            echo "✅ 3D video generated"
          else
            echo "⚠️ video_3d_build.py not found, using regular video"
          fi

      # FALLBACK: Regular video build
      - name: Build Shorts video
        if: env.USE_3D_VIDEO != 'true'
        run: |
          set -euo pipefail
          python video_build.py
          test -f output.mp4

      - name: Upload to YouTube Shorts
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
          YT_CHANNEL_ID: ${{ secrets.YT_CHANNEL_ID }}
        run: |
          set -euo pipefail
          python youtube_upload.py

      - name: Persist memory
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add memory used_cases.json upload_meta.json || true
          git commit -m "chore: update memory" || true
          git push || true
