name: Friday Upload

on:
  schedule:
    # Every Friday at 2PM EST = 19:00 UTC
    - cron: "0 19 * * 5"
  workflow_dispatch: # allow manual trigger from GitHub UI

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg python3 python3-pip
          pip3 install openai-whisper edge-tts --quiet

      - name: Download Whisper model
        run: python3 -c "import whisper; whisper.load_model('base')"

      - name: Install Go dependencies
        run: go mod download

      - name: Create required directories
        run: |
          mkdir -p assets/video assets/sfx output logs
          echo "{}" > assets/video/usage_log.json
          echo "[]" > logs/used_stories.json

      - name: Restore asset clips from cache
        uses: actions/cache@v4
        with:
          path: assets/
          key: assets-${{ runner.os }}-v1
          restore-keys: |
            assets-${{ runner.os }}-

      - name: Run pipeline
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: "TrueCrimePipeline/1.0"
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          TTS_COMMAND: "edge-tts"
        run: go run pipeline.go

      - name: Save usage log (so clips don't repeat next run)
        uses: actions/cache@v4
        if: always()
        with:
          path: assets/video/usage_log.json
          key: usage-log-${{ github.run_id }}
          restore-keys: |
            usage-log-

      - name: Upload pipeline output as artifact (for debugging)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pipeline-output-friday-${{ github.run_id }}
          path: |
            output/**/pipeline_state.json
            output/**/metadata.json
            output/**/story.json
          retention-days: 30
